import '@testing-library/jest-dom'

process.env.NEXT_PUBLIC_BALLOONS_NFT_ADDRESS = '0xTEST_NFT_ADDRESS'
process.env.NEXT_PUBLIC_INSTALLATION_CONTRACT_ADDRESS = '0xTEST_INSTALLATION_ADDRESS'
process.env.NEXT_PUBLIC_DEED_CONTRACT_ADDRESS = '0xDeEdDeEdDeEdDeEdDeEdDeEdDeEdDeEdDeEdDeEd'
